
pod 'AFNetworking', '~> 3.0'

pod 'RDVTabBarController'

pod 'MOBFoundation_IDFA'

pod 'SMSSDK'

pod 'ShareSDK3'

pod 'ShareSDK3/ShareSDKPlatforms/QQ'

pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'

pod 'ShareSDK3/ShareSDKPlatforms/WeChat'

pod 'MJRefresh'
